module.exports = {
    "Teams": [

        {
            "team_id": "arizona-diamondbacks",
            "abbreviation": "ARI",
            "active": "true",
            "first_name": "Arizona",
            "last_name": "Diamondbacks",
            "r_abbreviation" : "DBK",
            "r_name" : "rDiamondbacks",
            "conference": "National",
            "division": "West",
            "site_name": "Chase Field",
            "city": "Phoenix",
            "state": "Arizona",
            "full_name": "Arizona Diamondbacks",
            "logo": "//www.mlbstatic.com/mlb.com/builds/site-core/d8b325f6ac200ed2ae8d0cf25e5b68790fe7e8cc_1502375076/images/logos/team-primary-on-light/109.svg",
            "__v": 0,
            "colorPrimary": "A71930",
            "colorSecond": "DBCEAC",
            "colorThird": "09ADAD",
            "colorText": "white",
            "affiliates":
            {
                "AAA": "Reno Aces",
                "AA": "Jackson Generals",
                "A-High": "Visalia Rawhide",
                "A-Low": "Kane County Cougars",
                "Rookie-Advanced": "Hillsboro Hops",
                "Rookie": "Missoula Osprey, AZL D-backs",
                "DSL": "DSL D-backs1",
                "GCL": "",
                "SS": "",
                "AZL": ""
            }
        },

        {
            "team_id": "atlanta-braves",
            "abbreviation": "ATL",
            "active": "true",
            "first_name": "Atlanta",
            "last_name": "Braves",
            "r_abbreviation" : "BVS",
            "r_name" : "rBraves",
            "conference": "National",
            "division": "East",
            "site_name": "Turner Field",
            "city": "Atlanta",
            "state": "Georgia",
            "full_name": "Atlanta Braves",
            "__v": 0,
            "colorPrimary": "002855",
            "colorSecond": "BA0C2F",
            "colorThird": "FFFFFF",
            "colorText": "white",
            "affiliates":
            {
                "AAA": "Gwinnett Braves",
                "AA": "Mississippi Braves",
                "A-High": "Florida Fire Frogs",
                "A-Low": "Rome Braves",
                "Rookie-Advanced": "Danville Braves",
                "Rookie": "",
                "DSL": "DSL Braves",
                "GCL": "GCL Braves",
                "SS": "",
                "AZL": ""
            }
        },

        {
            "team_id": "baltimore-orioles",
            "abbreviation": "BAL",
            "active": "true",
            "first_name": "Baltimore",
            "last_name": "Orioles",
            "r_abbreviation" : "ORL",
            "r_name" : "rOrioles",
            "conference": "American",
            "division": "East",
            "site_name": "Oriole Park at Camden Yards",
            "city": "Baltimore",
            "state": "Maryland",
            "full_name": "Baltimore Orioles",
            "__v": 0,
            "colorPrimary": "FC4C00",
            "colorSecond": "000000",
            "colorThird": "FFFFFF",
            "colorText": "black",
            "affiliates":
            {
                "AAA": "Norfolk Tides",
                "AA": "Bowie Baysox",
                "A-High": "Frederick Keys",
                "A-Low": "Delmarva Shorebirds",
                "Rookie-Advanced": "Aberdeen IronBirds",
                "Rookie": "",
                "DSL": "DSL Orioles",
                "GCL": "GCL Orioles",
                "SS": "",
                "AZL": ""
            }
        },

        {
            "team_id": "boston-red-sox",
            "abbreviation": "BOS",
            "active": "true",
            "first_name": "Boston",
            "last_name": "Red Sox",
            "r_abbreviation" : "RSX",
            "r_name" : "rRed Sox",
            "conference": "American",
            "division": "East",
            "site_name": "Fenway Park",
            "city": "Boston",
            "state": "Massachusetts",
            "full_name": "Boston Red Sox",
            "__v": 0,
            "colorPrimary": "C60C30",
            "colorSecond": "002244",
            "colorThird": "FFFFFF",
            "colorText": "white",
            "affiliates":
            {
                "AAA": "Pawtucket Red Sox",
                "AA": "Portland Sea Dogs",
                "A-High": "Salem Red Sox",
                "A-Low": "Greenville Drive",
                "Rookie-Advanced": "Lowell Spinners",
                "Rookie": "",
                "DSL": "DSL Red Sox",
                "GCL": "GCL Red Sox",
                "SS": "",
                "AZL": ""
            }
        },

        {
            "team_id": "chicago-cubs",
            "abbreviation": "CHN",
            "standard_abbreviation": "CHC",
            "active": "true",
            "first_name": "Chicago",
            "last_name": "Cubs",
            "r_abbreviation" : "CUB",
            "r_name" : "rCubs",
            "conference": "National",
            "division": "Central",
            "site_name": "Wrigley Field",
            "city": "Chicago",
            "state": "Illinois",
            "full_name": "Chicago Cubs",
            "__v": 0,
            "colorPrimary": "002F6C",
            "colorSecond": "C8102E",
            "colorThird": "FFFFFF",
            "colorText": "white",
            "affiliates":
            {
                "AAA": "Iowa Cubs",
                "AA": "Tennessee Smokies",
                "A-High": "Myrtle Beach Pelicans",
                "A-Low": "South Bend Cubs",
                "Rookie-Advanced": "Eugene Emeralds",
                "DSL": "DSL Cubs1",
                "GCL": "",
                "SS": "",
                "Rookie": "AZL Cubs"
            }
        },

        {
            "team_id": "chicago-white-sox",
            "abbreviation": "CHA",
            "standard_abbreviation": "CHW",
            "active": "true",
            "first_name": "Chicago",
            "last_name": "White Sox",
            "r_abbreviation" : "WSX",
            "r_name" : "rWhite Sox",
            "conference": "American",
            "division": "Central",
            "site_name": "Guaranteed Rate Field",
            "city": "Chicago",
            "state": "Illinois",
            "full_name": "Chicago White Sox",
            "__v": 0,
            "colorPrimary": "000000",
            "colorSecond": "FFFFFF",
            "colorThird": "DCDDDF",
            "colorText": "white",
            "affiliates":
            {
                "AAA": "Charlotte Knights",
                "AA": "Birmingham Barons",
                "A-High": "Winston-Salem Dash",
                "A-Low": "Kannapolis Intimidators",
                "Rookie-Advanced": "Great Falls Voyagers",
                 "DSL": "DSL White Sox",
                "GCL": "",
                "SS": "",
                "Rookie": "AZL White Sox"
            }
        },

        {
            "team_id": "cincinnati-reds",
            "abbreviation": "CIN",
            "active": "true",
            "first_name": "Cincinnati",
            "last_name": "Reds",
            "r_abbreviation" : "RED",
            "r_name" : "rReds",
            "conference": "National",
            "division": "Central",
            "site_name": "Great American Ball Park",
            "city": "Cincinnati",
            "state": "Ohio",
            "full_name": "Cincinnati Reds",
            "__v": 0,
            "colorPrimary": "BA0C2F",
            "colorSecond": "FFFFFF",
            "colorThird": "000000",
            "colorText": "white",
            "affiliates":
            {
                "AAA": "Louisville Bats",
                "AA": "Pensacola Blue Wahoos",
                "A-High": "Daytona Tortugas",
                "A-Low": "Dayton Dragons",
                "Rookie-Advanced": "Billings Mustangs",
                "DSL": "DSL Reds",
                "GCL": "",
                "SS": "",
                "Rookie": "AZL Reds"
            }
        },

        {
            "team_id": "cleveland-indians",
            "abbreviation": "CLE",
            "active": "true",
            "first_name": "Cleveland",
            "last_name": "Indians",
            "r_abbreviation" : "IND",
            "r_name" : "rIndians",
            "conference": "American",
            "division": "Central",
            "site_name": "Progressive Field",
            "city": "Cleveland",
            "state": "Ohio",
            "full_name": "Cleveland Indians",
            "__v": 0,
            "colorPrimary": "D50032",
            "colorSecond": "0C2340",
            "colorThird": "FFFFFF",
            "colorText": "white",
            "affiliates":
            {
                "AAA": "Colombus Clippers",
                "AA": "Akron RubberDucks",
                "A-High": "Lynchburg Hillcats",
                "A-Low": "Lake County Captains",
                "Rookie-Advanced": "Mahoning Valley Scrappers",
                "DSL": "DSL Indians",
                "GCL": "",
                "SS": "",
                "Rookie": "AZL Indians"
            }
        },

        {
            "team_id": "colorado-rockies",
            "abbreviation": "COL",
            "active": "true",
            "first_name": "Colorado",
            "last_name": "Rockies",
            "r_abbreviation" : "ROX",
            "r_name" : "rRockies",
            "conference": "National",
            "division": "West",
            "site_name": "Coors Field",
            "city": "Denver",
            "state": "Colorado",
            "full_name": "Colorado Rockies",
            "__v": 0,
            "colorPrimary": "24135E",
            "colorSecond": "000000",
            "colorThird": "CACDCD",
            "colorText": "white",
            "affiliates":
            {
                "AAA": "Albuquerque Isotopes",
                "AA": "Hartford Yard Goats",
                "A-High": "Lancaster JetHawks",
                "A-Low": "Asheville Tourists",
                "Rookie-Advanced": "Grand Junction Rockies,Boise Hawks",
                "Rookie": "",
                "DSL": "DSL Rockies,DSL Indians",
                "GCL": "",
                "SS": "",
                "AZL": ""
            }
        },

        {
            "team_id": "detroit-tigers",
            "abbreviation": "DET",
            "active": "true",
            "first_name": "Detroit",
            "last_name": "Tigers",
            "r_abbreviation" : "TIG",
            "r_name" : "rTigers",
            "conference": "American",
            "division": "Central",
            "site_name": "Comerica Park",
            "city": "Detroit",
            "state": "Michigan",
            "full_name": "Detroit Tigers",
            "__v": 0,
            "colorPrimary": "0C2340",
            "colorSecond": "FFFFFF",
            "colorThird": "FA4614",
            "colorText": "white",
            "affiliates":
            {
                "AAA": "Toledo Mud Hens",
                "AA": "Erie SeaWolves",
                "A-High": "Lakeland Flying Tigers",
                "A-Low": "West Michigan Whitecaps",
                "Rookie-Advanced": "Connecticut Tigers",
                "Rookie": "",
                "DSL": "DSL Tigers",
                "GCL": "GCL Tigers East",
                "SS": "",
                "AZL": ""
            }
        },

        {
            "team_id": "houston-astros",
            "abbreviation": "HOU",
            "active": "true",
            "first_name": "Houston",
            "last_name": "Astros",
            "r_abbreviation" : "AST",
            "r_name" : "rAstros",
            "conference": "American",
            "division": "West",
            "site_name": "Minute Maid Park",
            "city": "Houston",
            "state": "Texas",
            "full_name": "Houston Astros",
            "__v": 0,
            "colorPrimary": "041E42",
            "colorSecond": "CF4520",
            "colorThird": "FFFFFF",
            "colorText": "white",
            "affiliates":
            {
                "AAA": "Fresno Grizzlies",
                "AA": "Corpus Christi Hooks",
                "A-High": "Buies Creek Astros",
                "A-Low": "Quad Cities River Bandits",
                "Rookie-Advanced": "Greeneville Astros,Tri-City ValleyCats",
                "Rookie": "",
                "DSL": "DSL Astros Blue",
                "GCL": "GCL Astros",
                "SS": "",
                "AZL": ""
            }
        },

        {
            "team_id": "kansas-city-royals",
            "abbreviation": "KC",
            "active": "true",
            "first_name": "Kansas City",
            "last_name": "Royals",
            "r_abbreviation" : "ROY",
            "r_name" : "rRoyals",
            "conference": "American",
            "division": "Central",
            "site_name": "Kauffman Stadium",
            "city": "Kansas City",
            "state": "Missouri",
            "full_name": "Kansas City Royals",
            "__v": 0,
            "colorPrimary": "15317E",
            "colorSecond": "FFFFFF",
            "colorThird": "74B4FA",
            "colorText": "white",
            "affiliates":
            {
                "AAA": "Omaha Storm Chasers",
                "AA": "Northwest Arkansas Naturals",
                "A-High": "Wilmington Blue Rocks",
                "A-Low": "Lexington Legends",
                "Rookie-Advanced": "Burlington Royals",
                "Rookie": "Idaho Falls Chukars, AZL Royals",
                "DSL": "DSL Royals",
                "GCL": "",
                "SS": "",
                "AZL": ""
            }
        },

        {
            "team_id": "los-angeles-angels",
            "abbreviation": "LAA",
            "active": "true",
            "first_name": "Los Angeles",
            "last_name": "Angels",
            "r_abbreviation" : "ANG",
            "r_name" : "rAngels",
            "conference": "American",
            "division": "West",
            "site_name": "Angel Stadium of Anaheim",
            "city": "Anaheim",
            "state": "California",
            "full_name": "Los Angeles Angels",
            "__v": 0,
            "colorPrimary": "BA032E",
            "colorSecond": "0C2344",
            "colorThird": "FFFFFF",
            "colorText": "white",
            "affiliates":
            {
                "AAA": "Salt Lake Bees",
                "AA": "Mobile BayBears",
                "A-High": "Inland Empire 66ers",
                "A-Low": "Burlington Bees",
                "Rookie-Advanced": "Orem Owlz",
                "DSL": "DSL Angels",
                "GCL": "",
                "SS": "",
                "Rookie": "AZL Angels"
            }
        },

        {
            "team_id": "los-angeles-dodgers",
            "abbreviation": "LAN",
            "standard_abbreviation": "LAD",
            "active": "true",
            "first_name": "Los Angeles",
            "last_name": "Dodgers",
            "r_abbreviation" : "DOD",
            "r_name" : "rDodgers",
            "conference": "National",
            "division": "West",
            "site_name": "Dodger Stadium",
            "city": "Los Angeles",
            "state": "California",
            "full_name": "Los Angeles Dodgers",
            "__v": 0,
            "colorPrimary": "002F6C",
            "colorSecond": "FFFFFF",
            "colorThird": "E4002B",
            "colorText": "white",
            "affiliates":
            {
                "AAA": "Oklahmoa City Dodgers",
                "AA": "Tulsa Drillers",
                "A-High": "Rancho Cucamonga Quakes",
                "A-Low": "Great Lakes Loons",
                "Rookie-Advanced": "Ogden Raptors",
                "DSL": "DSL Dodgers1",
                "GCL": "",
                "SS": "",
                "Rookie": "AZL Dodgers"
            }
        },

        {
            "team_id": "miami-marlins",
            "abbreviation": "MIA",
            "active": "true",
            "first_name": "Miami",
            "last_name": "Marlins",
            "r_abbreviation" : "MRL",
            "r_name" : "rMarlins",
            "conference": "National",
            "division": "East",
            "site_name": "Marlins Park",
            "city": "Miami",
            "state": "Florida",
            "full_name": "Miami Marlins",
            "__v": 0,
            "colorPrimary": "000000",
            "colorSecond": "F9423B",
            "colorThird": "FCDE04",
            "colorText": "white",
            "affiliates":
            {
                "AAA": "New Orleans Baby Cakes",
                "AA": "Jacksonville Jumbo Shrimp",
                "A-High": "Jupiter Hammerheads",
                "A-Low": "Greemsboro Grasshoppers",
                "Rookie-Advanced": "Batavia Muckdogs",
                "Rookie": "",
                "DSL": "DSL Marlins",
                "GCL": "GCL Marlins",
                "SS": "",
                "AZL": ""
            }
        },

        {
            "team_id": "milwaukee-brewers",
            "abbreviation": "MIL",
            "active": "true",
            "first_name": "Milwaukee",
            "last_name": "Brewers",
            "r_abbreviation" : "BWS",
            "r_name" : "rBrewers",
            "conference": "National",
            "division": "Central",
            "site_name": "Miller Park",
            "city": "Milwaukee",
            "state": "Wisconsin",
            "full_name": "Milwaukee Brewers",
            "__v": 0,
            "colorPrimary": "012143",
            "colorSecond": "C4953B",
            "colorThird": "FFFFFF",
            "colorText": "white",
            "affiliates":
            {
                "AAA": "Colorado Springs Sky Sox",
                "AA": "Biloxi Shuckers",
                "A-High": "Carolina Mudcats",
                "A-Low": "Wisconsin Timber Rattlers",
                "Rookie-Advanced": "Helena Brewers",
                "DSL": "DSL Brewers",
                "GCL": "",
                "SS": "",
                "Rookie": "AZL Brewers"
            }
        },

        {
            "team_id": "minnesota-twins",
            "abbreviation": "MIN",
            "active": "true",
            "first_name": "Minnesota",
            "last_name": "Twins",
            "r_abbreviation" : "TWN",
            "r_name" : "rTwins",
            "conference": "American",
            "division": "Central",
            "site_name": "Target Field",
            "city": "Minneapolis",
            "state": "Minnesota",
            "full_name": "Minnesota Twins",
            "__v": 0,
            "colorPrimary": "0C2341",
            "colorSecond": "BA0C2E",
            "colorThird": "B9975B",
            "colorText": "white",
            "affiliates":
            {
                "AAA": "Rochester Red Wings",
                "AA": "Chattanooga Lookouts",
                "A-High": "Fort Myers Miracle",
                "A-Low": "Cedar Rapids Kernels",
                "Rookie-Advanced": "Elizabethton Twins",
                "Rookie": "",
                "DSL": "DSL Twins",
                "GCL": "GCL Twins",
                "SS": "",
                "AZL": ""
            }
        },

        {
            "team_id": "new-york-mets",
            "abbreviation": "NYN",
            "standard_abbreviation": "NYM",
            "active": "true",
            "first_name": "New York",
            "last_name": "Mets",
            "r_abbreviation" : "MET",
            "r_name" : "rMets",
            "conference": "National",
            "division": "East",
            "site_name": "Citi Field",
            "city": "Flushing",
            "state": "New York",
            "full_name": "New York Mets",
            "__v": 0,
            "colorPrimary": "002D70",
            "colorSecond": "FC4C00",
            "colorThird": "FFFFFF",
            "colorText": "white",
            "affiliates":
            {
                "AAA": "Las Vegas 51s",
                "AA": "Binghampton Ruble Ponies",
                "A-High": "St. Lucie Mets",
                "A-Low": "Columbia Fireflies",
                "Rookie-Advanced": "Kingsport Mets,Brooklyn Cyclones",
                "Rookie": "",
                "DSL": "DSL Mets1",
                "GCL": "GCL Mets",
                "SS": "",
                "AZL": ""
            }
        },

        {
            "team_id": "new-york-yankees",
            "abbreviation": "NYA",
            "standard_abbreviation": "NYY",
            "active": "true",
            "first_name": "New York",
            "last_name": "Yankees",
            "r_abbreviation" : "YNK",
            "r_name" : "rYankees",
            "conference": "American",
            "division": "East",
            "site_name": "Yankee Stadium",
            "city": "Bronx",
            "state": "New York",
            "full_name": "New York Yankees",
            "__v": 0,
            "colorPrimary": "0C2340",
            "colorSecond": "FFFFFF",
            "colorThird": "97999B",
            "colorText": "white",
            "affiliates":
            {
                "AAA": "Scranton/Wilkes-Barre RailRiders",
                "AA": "Trenton Thunder",
                "A-High": "Tampa Yankees",
                "A-Low": "Charleston RiverDogs",
                "Rookie-Advanced": "Pulaski Yankees,Staten Island Yankees",
                "Rookie": "",
                "DSL": "DSL Yankees",
                "GCL": "GCL Yankees East",
                "SS": "",
                "AZL": ""
            }
        },

        {
            "team_id": "oakland-athletics",
            "abbreviation": "OAK",
            "active": "true",
            "first_name": "Oakland",
            "last_name": "Athletics",
            "conference": "American",
            "r_abbreviation" : "ATH",
            "r_name" : "rAthletics",
            "division": "West",
            "site_name": "O.co Coliseum",
            "city": "Oakland",
            "state": "California",
            "full_name": "Oakland Athletics",
            "__v": 0,
            "colorPrimary": "00483A",
            "colorSecond": "FFBE00",
            "colorThird": "FFFFFF",
            "colorText": "FFBE00",
            "affiliates":
            {
                "AAA": "Nashville Sounds",
                "AA": "Midland RockHounds",
                "A-High": "Stockton Ports",
                "A-Low": "Beloit Snappers",
                "Rookie-Advanced": "",
                "DSL": "DSL Athletics",
                "GCL": "",
                "SS": "",
                "Rookie": "AZL Athletics"
            }
        },

        {
            "team_id": "philadelphia-phillies",
            "abbreviation": "PHI",
            "active": "true",
            "first_name": "Philadelphia",
            "last_name": "Phillies",
            "conference": "National",
            "r_abbreviation" : "PHL",
            "r_name" : "rPhillies",
            "division": "East",
            "site_name": "Citizens Bank Park",
            "city": "Philadelphia",
            "state": "Pennsylvania",
            "full_name": "Philadelphia Phillies",
            "__v": 0,
            "colorPrimary": "BA0C2E",
            "colorSecond": "FFFFFF",
            "colorThird": "003086",
            "colorText": "white",
            "affiliates":
            {
                "AAA": "Lehigh Valley IronPigs",
                "AA": "Reading Fightin Phils",
                "A-High": "Clearwater Threshers",
                "A-Low": "Lakewood BlueClaws",
                "Rookie-Advanced": "Williamsport Crosscutters",
                "Rookie": "",
                "DSL": "DSL Phillies Red",
                "GCL": "GCL Phillies",
                "SS": "",
                "AZL": ""
            }
        },

        {
            "team_id": "pittsburgh-pirates",
            "abbreviation": "PIT",
            "active": "true",
            "first_name": "Pittsburgh",
            "last_name": "Pirates",
            "r_abbreviation" : "PIR",
            "r_name" : "rPirates",
            "conference": "National",
            "division": "Central",
            "site_name": "PNC Park",
            "city": "Pittsburgh",
            "state": "Pennsylvania",
            "full_name": "Pittsburgh Pirates",
            "__v": 0,
            "colorPrimary": "000000",
            "colorSecond": "FFC72B",
            "colorThird": "FFFFFF",
            "colorText": "white",
            "affiliates":
            {
                "AAA": "Indianapolis Indians",
                "AA": "Altoona Curve",
                "A-High": "Bradenton Marauders",
                "A-Low": "West Virginia Power",
                "Rookie-Advanced": "Bristol Pirates,West Virginia Black Bears",
                "Rookie": "",
                "DSL": "DSL Pirates",
                "GCL": "GCL Pirates",
                "SS": "",
                "AZL": ""
            }
        },

        {
            "team_id": "san-diego-padres",
            "abbreviation": "SD",
            "active": "true",
            "first_name": "San Diego",
            "last_name": "Padres",
            "r_abbreviation" : "PAD",
            "r_name" : "rPadres",
            "conference": "National",
            "division": "West",
            "site_name": "PETCO Park",
            "city": "San Diego",
            "state": "California",
            "full_name": "San Diego Padres",
            "__v": 0,
            "colorPrimary": "002D62",
            "colorSecond": "FFFFFF",
            "colorThird": "FEC325",
            "colorText": "white",
            "affiliates":
            {
                "AAA": "El Pase Chihuahuas",
                "AA": "San Antonio Missions",
                "A-High": "Lake Elsinore Storm",
                "A-Low": "Fort Wayne TinCaps",
                "Rookie-Advanced": "Tri-City Dust Devils",
                "DSL": "DSL Padres",
                "GCL": "",
                "SS": "",
                "Rookie": "AZL Padres"
            }
        },

        {
            "team_id": "san-francisco-giants",
            "abbreviation": "SF",
            "active": "true",
            "first_name": "San Francisco",
            "last_name": "Giants",
            "r_abbreviation" : "GNT",
            "r_name" : "rGiants",
            "conference": "National",
            "division": "West",
            "site_name": "AT&T Park",
            "city": "San Francisco",
            "state": "California",
            "full_name": "San Francisco Giants",
            "__v": 0,
            "colorPrimary": "000000",
            "colorSecond": "FB5B1F",
            "colorThird": "FFFDD0",
            "colorText": "white",
            "affiliates":
            {
                "AAA": "Sacramento River Cats",
                "AA": "Richmond Flying Squirrels",
                "A-High": "San Jose Giants",
                "A-Low": "Augusta GreenJackets",
                "Rookie-Advanced": "Salem-Keizer Volcanoes",
                "Rookie": "",
                "DSL": "DSL Giants",
                "GCL": "",
                "SS": "",
                "Rookie": "AZL Giants"
            }
        },

        {
            "team_id": "seattle-mariners",
            "abbreviation": "SEA",
            "active": "true",
            "first_name": "Seattle",
            "last_name": "Mariners",
            "r_abbreviation" : "MRS",
            "r_name" : "rMariners",
            "conference": "American",
            "division": "West",
            "site_name": "Safeco Field",
            "city": "Seattle",
            "state": "Washington",
            "full_name": "Seattle Mariners",
            "__v": 0,
            "colorPrimary": "0C2C56",
            "colorSecond": "005C5C",
            "colorThird": "C0C0C0",
            "colorText": "white",
            "affiliates":
            {
                "AAA": "Tacoma Rainiers",
                "AA": "Arkansas Travelers",
                "A-High": "Modesto Nuts",
                "A-Low": "Clinto LumberKings",
                "Rookie-Advanced": "Everett AquaSox",
                "DSL": "DSL Mariners",
                "GCL": "",
                "SS": "",
                "Rookie": "AZL Mariners"
            }
        },

        {
            "team_id": "st-louis-cardinals",
            "abbreviation": "STL",
            "active": "true",
            "first_name": "St. Louis",
            "last_name": "Cardinals",
            "r_abbreviation" : "CRD",
            "r_name" : "rCardinals",
            "conference": "National",
            "division": "Central",
            "site_name": "Busch Stadium",
            "city": "Saint Louis",
            "state": "Missouri",
            "full_name": "St. Louis Cardinals",
            "__v": 0,
            "colorPrimary": "C41E3A",
            "colorSecond": "0A2252",
            "colorThird": "FFFFFF",
            "colorText": "white",
            "affiliates":
            {
                "AAA": "Memphis Redbirds",
                "AA": "Springfield Cardinals",
                "A-High": "Palm Beach Cardinals",
                "A-Low": "Peoria Chiefs",
                "Rookie-Advanced": "Johnson City Cardinals,State College Spikes",
                "Rookie": "",
                "DSL": "DSL Cardinals",
                "GCL": "GCL Cardinals",
                "SS": "",
                "AZL": ""
            }
        },

        {
            "team_id": "tampa-bay-rays",
            "abbreviation": "TB",
            "active": "true",
            "first_name": "Tampa Bay",
            "last_name": "Rays",
            "r_abbreviation" : "RAY",
            "r_name" : "rRays",
            "conference": "American",
            "division": "East",
            "site_name": "Tropicana Field",
            "city": "Saint Petersburg",
            "state": "Florida",
            "full_name": "Tampa Bay Rays",
            "__v": 0,
            "colorPrimary": "00285D",
            "colorSecond": "79BDEE",
            "colorThird": "FFFFFF",
            "colorText": "white",
            "affiliates":
            {
                "AAA": "Durham Bulls",
                "AA": "Montgomery Biscuits",
                "A-High": "Charlotte Stone Crabs",
                "A-Low": "Bowling Green Hot Rods",
                "Rookie-Advanced": "Princeton Rays,Hudson Valley Renegades",
                "Rookie": "",
                "DSL": "DSL Rays1",
                "GCL": "GCL Rays",
                "SS": "",
                "AZL": ""
            }
        },

        {
            "team_id": "texas-rangers",
            "abbreviation": "TEX",
            "active": "true",
            "first_name": "Texas",
            "last_name": "Rangers",
            "r_abbreviation" : "RNG",
            "r_name" : "rRangers",
            "conference": "American",
            "division": "West",
            "site_name": "Globe Life Park in Arlington",
            "city": "Arlington",
            "state": "Texas",
            "full_name": "Texas Rangers",
            "__v": 0,
            "colorPrimary": "BD1021",
            "colorSecond": "FFFFFF",
            "colorThird": "003279",
            "colorText": "white",
            "affiliates":
            {
                "AAA": "Round Rock Express",
                "AA": "Frisco RoughRiders",
                "A-High": "Down East Wood Ducks",
                "A-Low": "Hickory Crawdads",
                "Rookie-Advanced": "Spokane Indians",
                "DSL": "DSL Rangers1",
                "GCL": "",
                "SS": "",
                "Rookie": "AZL Rangers"
            }
        },

        {
            "team_id": "toronto-blue-jays",
            "abbreviation": "TOR",
            "active": "true",
            "first_name": "Toronto",
            "last_name": "Blue Jays",
            "r_abbreviation" : "JAY",
            "r_name" : "rBlue Jays",
            "conference": "American",
            "division": "East",
            "site_name": "Rogers Centre",
            "city": "Toronto",
            "state": "Ontario",
            "full_name": "Toronto Blue Jays",
            "__v": 0,
            "colorPrimary": "003279",
            "colorSecond": "041E42",
            "colorThird": "FFFFFF",
            "colorText": "white",
            "affiliates":
            {
                "AAA": "Buffalo Bisons",
                "AA": "New Hampshire Fisher Cats",
                "A-High": "Dunedin Blue Jays",
                "A-Low": "Lansing Lugnuts",
                "Rookie-Advanced": "Bluefield Blue Jays,Vancouver Canadians",
                "Rookie": "",
                "DSL": "DSL Blue Jays",
                "GCL": "GCL Blue Jays",
                "SS": "",
                "AZL": ""
            }
        },

        {
            "team_id": "washington-nationals",
            "abbreviation": "WAS",
            "active": "true",
            "first_name": "Washington",
            "last_name": "Nationals",
            "r_abbreviation" : "NAT",
            "r_name" : "rNationals",
            "conference": "National",
            "division": "East",
            "site_name": "Nationals Park",
            "city": "Washington",
            "state": "District of Columbia",
            "full_name": "Washington Nationals",
            "__v": 0,
            "colorPrimary": "BA122B",
            "colorSecond": "14225A",
            "colorThird": "FFFFFF",
            "colorText": "white",
            "affiliates":
            {
                "AAA": "Syracuse Chiefs",
                "AA": "Harrisburg Senators",
                "A-High": "Potomac Nationals",
                "A-Low": "Hagerstown Suns",
                "Rookie-Advanced": "Auburn Doubledays",
                "Rookie": "",
                "DSL": "DSL Nationals",
                "GCL": "GCL Nationals",
                "SS": "",
                "AZL": ""
            }
        }
    ],
    ALTeams: [
        "rOrioles",
        "rRed Sox",
        "rYankees",
        "rRays",
        "rBlue Jays",
        
        "rWhite Sox",
        "rIndians",
        "rTigers",
        "rRoyals",
        "rTwins",
        
        "rAstros",
        "rAngels",
        "rAthletics",
        "rMariners",
        "rRangers"
    ]
} 